import React from 'react';

const Schedule = () => {
    return ( 
        <React.Fragment>
            <table align="center" style={{color: "white", border: "1px solid white"}}>
                <thead>
                    <tr>
                        <th>Player 1</th>
                        <th>#</th>
                        <th>Player 2</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Carter</td>
                        <td>1</td>
                        <td>Ella</td>
                    </tr>
                    <tr>
                        <td>Ben D</td>
                        <td>2</td>
                        <td>Sanjana</td>
                    </tr>
                    <tr>
                        <td>Nicole</td>
                        <td>3</td>
                        <td>Joel</td>
                    </tr>
                    <tr>
                        <td>Ben W</td>
                        <td>4</td>
                        <td>Teresa</td>
                    </tr>
                    <tr>
                        <td>Julie</td>
                        <td>5</td>
                        <td>Alex</td>
                    </tr>
                    <tr>
                        <td>Anna</td>
                        <td>6</td>
                        <td>Nate</td>
                    </tr>
                    <tr>
                        <td>Connor</td>
                        <td>7</td>
                        <td>Fred</td>
                    </tr>
                    <tr>
                        <td>Owen</td>
                        <td>8</td>
                        <td>Max</td>
                    </tr>
                    <tr>
                        <td>Kelso</td>
                        <td>9</td>
                        <td>W1</td>
                    </tr>
                    <tr>
                        <td>Chad</td>
                        <td>10</td>
                        <td>W2</td>
                    </tr>
                    <tr>
                        <td>Ethan</td>
                        <td>11</td>
                        <td>W3</td>
                    </tr>
                    <tr>
                        <td>L3</td>
                        <td>12</td>
                        <td>L4</td>
                    </tr>
                    <tr>
                        <td>L2</td>
                        <td>13</td>
                        <td>L6</td>
                    </tr>
                    <tr>
                        <td>L1</td>
                        <td>14</td>
                        <td>L8</td>
                    </tr>
                    <tr>
                        <td>L7</td>
                        <td>15</td>
                        <td>L10</td>
                    </tr>
                    <tr>
                        <td>L9</td>
                        <td>16</td>
                        <td>W12</td>
                    </tr>
                    <tr>
                        <td>L5</td>
                        <td>17</td>
                        <td>W13</td>
                    </tr>
                    <tr>
                        <td>L11</td>
                        <td>18</td>
                        <td>W14</td>
                    </tr>
                    <tr>
                        <td>W5</td>
                        <td>19</td>
                        <td>W6</td>
                    </tr>
                    <tr>
                        <td>W4</td>
                        <td>20</td>
                        <td>W9</td>
                    </tr>
                    <tr>
                        <td>W7</td>
                        <td>21</td>
                        <td>W10</td>
                    </tr>
                    <tr>
                        <td>W8</td>
                        <td>22</td>
                        <td>W8 </td>
                    </tr>
                    <tr>
                        <td>L19</td>
                        <td>23</td>
                        <td>W18</td>
                    </tr>
                    <tr>
                        <td>L20</td>
                        <td>24</td>
                        <td>W15</td>
                    </tr>
                    <tr>
                        <td>L21</td>
                        <td>25</td>
                        <td>W16</td>
                    </tr>
                    <tr>
                        <td>L22</td>
                        <td>26</td>
                        <td>W17</td>
                    </tr>
                    <tr>
                        <td>W23</td>
                        <td>27</td>
                        <td>W24</td>
                    </tr>
                    <tr>
                        <td>W26</td>
                        <td>28</td>
                        <td>W25</td>
                    </tr>
                    <tr>
                        <td>W19</td>
                        <td>29</td>
                        <td>W20</td>
                    </tr>
                    <tr>
                        <td>W21</td>
                        <td>30</td>
                        <td>W22</td>
                    </tr>
                    <tr>
                        <td>L29</td>
                        <td>31</td>
                        <td>W28</td>
                    </tr>
                    <tr>
                        <td>L30</td>
                        <td>32</td>
                        <td>W27</td>
                    </tr>
                    <tr>
                        <td>W31</td>
                        <td>33</td>
                        <td>W32</td>
                    </tr>
                    <tr>
                        <td>W29</td>
                        <td>34</td>
                        <td>W30</td>
                    </tr>
                    <tr>
                        <td>L34</td>
                        <td>35</td>
                        <td>W33</td>
                    </tr>
                    <tr>
                        <td>W34</td>
                        <td>36</td>
                        <td>W35</td>
                    </tr>
                    <tr>
                        <td>W36</td>
                        <td>37<br />(IN)</td>
                        <td>L36</td>
                    </tr>
                </tbody>
            </table>
        </React.Fragment>    
     );
}
 
export default Schedule;